name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
    - uses: actions/checkout@v5
    - run: swift build --build-tests
    - run: swift test --skip-build --enable-swift-testing --parallel
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  lint:
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
      - uses: actions/checkout@v5
      - run: swift format lint -r -p -s .
